class HParamSet(object):
    def __init__(self, options):
        self.max_sts_score = options.max_sts_score
        self.balance_data = options.balance_data
        self.output_size = options.output_size
        self.batch_size = options.batch_size
        self.activation = options.activation
        self.hidden_layer_size = options.hidden_layer_size
        self.num_hidden_layers = options.num_hidden_layers
        self.embedding_dim = options.embedding_dim
        self.dropout = options.dropout
        self.optimizer = options.optimizer
        self.learning_rate = options.learning_rate
        self.lr_decay_pow = options.lr_decay_pow
        self.epochs = options.epochs
        self.seed = options.seed
        self.max_steps = options.max_steps
        self.patience = options.patience
        self.eval_each_epoch = options.eval_each_epoch
        self.number_of_tags = 0
        self.vocab_size = 0
